### ISSUE TITLE
Screenshot for retina devices

### ISSUE THREAD

**Issue by kitze** [graphcool/homepage#6]
The screenshot on the landing page looks very blurry on a retina device (https://graph.cool/3a8126f6b2ffff3f4c0defa768c63216.png)

Something with a better quality (and a new version of the UI) should be uploaded.

**Comment by schickling** [comment]
Good catch. We're currently re-doing the entire website! Stay tuned 🎉

**Comment by kitze** [comment]
Awesome! 🙌
